name: Build Chain

on:
  push:
    branches:
      - main

jobs:
  UnitTests:
    name: Python Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s '.' -p 'test_*.py' -v

  Coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover -s '.' -p 'test_*.py' -v
          coverage report -m

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
      

  Linting:
    name: Pylint Analysis
    runs-on: ubuntu-latest
    needs: UnitTests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint --disable=invalid-name --disable=too-few-public-methods --disable=C0116 --disable=multiple-statements $(git ls-files '*.py')
